/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNIDemo_JNIDemo */

// 【Java 生成 JNI 头文件】https://www.jianshu.com/p/e1395dba92f2
// 生成c++头文件的命令 （生成后，找下，找到后，移至cpp文件夹下，或看下如何指定路径生成）
// javac -encoding utf8 -h . .\JNIDemo\JNIDemo.java

#ifndef _Included_JNIDemo_JNIDemo
#define _Included_JNIDemo_JNIDemo

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo_JNIDemo
 * Method:    invokeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_JNIDemo_invokeNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
